baseurl = "https://amitrajan012.github.io"
title = "Amit Rajan"
theme = "hugo-theme-cleanwhite"
languageCode = "en-us"
paginate = 5000 #frontpage pagination

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  header_image = "img/head.jpg"
  title = "Software Engineering"
  slogan = "Machine Learning | Blockchain"
  SEOTitle = "Amit Rajan Blog"
  keyword = "Amit, Rajan, ML, Data, Science, Blockchain"
 
  # Sidebar settings
  sidebar_about_description = "Data Scientist, Reader"
  sidebar_avatar = "img/a.png"
  about_me = true

  featured_tags = true 
  featured_condition_size = 2 # How many posts have to have a given tag to be featured (greater-than)

  # image_404 = "img/404-bg.jpg"
  title_404 = "We couldn't find what you were looking for..."

  omit_categories = false

  [[params.addtional_menus]]
  title =  "ABOUT"
  href =  "/top/about/"

  [params.social]
  rss            = true
  email          = "amitrajan012@gmail.com"
  linkedin       = "https://www.linkedin.com/in/amit-rajan-1343aaba/"
  github         = "https://github.com/amitrajan012"